name: Deploy to XM Cloud

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
    secrets:
      XM_CLOUD_ORG_CLIENT_SECRET:
        required: true
      XM_CLOUD_ORG_CLIENT_ID:
        required: true
      XM_CLOUD_ENVIRONMENT_ID:
        required: true

jobs:
  deploy:
    name: ${{ inputs.environment_name }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - run: dotnet tool restore
      - run: dotnet sitecore --help
      - name: Authenticate CLI with XM Cloud
        run: dotnet sitecore cloud login --client-credentials --client-id ${{ secrets.XM_CLOUD_ORG_CLIENT_ID }} --client-secret ${{ secrets.XM_CLOUD_ORG_CLIENT_SECRET }} --allow-write
      - name: Deploy the CM assets to XM Cloud
        run: |
          result=$(dotnet sitecore cloud deployment create --environment-id ${{ secrets.XM_CLOUD_ENVIRONMENT_ID }} --upload --json)
          echo $result
          isTimedOut=$(echo $result | jq ' .IsTimedOut')
          isCompleted=$(echo $result | jq ' .IsCompleted')
          if [ $isTimedOut = true ]
          then
              echo "Operation Timed Out."
              exit -1
          fi
          if ! [ $isCompleted = true ]
          then
              echo "Operation Failed."
              exit -1
          fi
          echo "Deployment Completed"
