name: Frontend Deploy 

on:  
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
  workflow_dispatch:

jobs:
  cloud:
    uses: ./.github/workflows/deploy-netlify.yml
    with:
      environment_name: ${{ inputs.environment_name }}
    secrets:
      NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
      